version: '2.1'

services:
  database:
    image: mongo:latest
    ports:
      - 27017:27017
    restart: always
    volumes:
      - ./database:/data/db
    command: mongod --smallfiles --logpath=/dev/null

  server:
    image: node:latest
    build: .
    volumes:
       - ./:/usr/src/app
       - node_modules:/usr/src/node_modules
    ports:
      - 8080:8080
    depends_on:
      - database
    links:
      - database
    environment:
      PORT: 8080
volumes:
  node_modules:
